server:
  port: 80

logging:
  level:
    com.reggie: debug

spring:
  application:
    name:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.245.129:3306/reggie?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: manager
#      password: Admin123.
  shardingsphere:

    datasource:
      # 有几个库
      names: master,slave
      # 库1 的配置
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.245.133:3306/reggie?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: manager
        password: Admin123.
      # 库2 的配置
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.245.135:3306/reggie?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: manager
        password: Admin123.
    #读写分离配置
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    # 是否打印sql
    props:
      sql:
        show: true

  mybatis-plus:
    configuration:
      #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: ASSIGN_ID
  mail:
    host: smtp.163.com
    protocol: smtps
    port: 465
    username: xx@163com
    password:
    from: xx@163.com
  redis:
    host: 192.168.245.133
    password: admin123.
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0

  cache:
    redis:
      time-to-live: 1800000

reggie:
  path: /usr/local/img/






